# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rubytter}
  s.version = "1.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["jugyo"]
  s.date = %q{2010-11-03}
  s.description = %q{Rubytter is a simple twitter client.}
  s.email = %q{jugyo.org@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/direct_message.rb",
     "examples/favorite.rb",
     "examples/follow.rb",
     "examples/friends_timeline.rb",
     "examples/home_timeline.rb",
     "examples/limit.rb",
     "examples/lists.rb",
     "examples/replies.rb",
     "examples/search.rb",
     "examples/update_status.rb",
     "examples/use_oauth.rb",
     "examples/use_xauth.rb",
     "examples/user.rb",
     "lib/rubytter.rb",
     "lib/rubytter/connection.rb",
     "lib/rubytter/core_ext.rb",
     "lib/rubytter/oauth.rb",
     "lib/rubytter/oauth_rubytter.rb",
     "spec/rubytter/oauth_spec.rb",
     "spec/rubytter_spec.rb",
     "spec/search.json",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jugyo/rubytter}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{rubytter}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple twitter client.}
  s.test_files = [
    "spec/rubytter/oauth_spec.rb",
     "spec/rubytter_spec.rb",
     "spec/spec_helper.rb",
     "examples/direct_message.rb",
     "examples/favorite.rb",
     "examples/follow.rb",
     "examples/friends_timeline.rb",
     "examples/home_timeline.rb",
     "examples/limit.rb",
     "examples/lists.rb",
     "examples/replies.rb",
     "examples/search.rb",
     "examples/update_status.rb",
     "examples/use_oauth.rb",
     "examples/use_xauth.rb",
     "examples/user.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 1.1.3"])
      s.add_runtime_dependency(%q<oauth>, [">= 0.3.6"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<json>, [">= 1.1.3"])
      s.add_dependency(%q<oauth>, [">= 0.3.6"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, [">= 1.1.3"])
    s.add_dependency(%q<oauth>, [">= 0.3.6"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

